import { describe, expect, it } from 'vitest'
import fs from 'fs'
import path from 'path'
const read=(f:string)=>fs.readFileSync(path.resolve(process.cwd(),f),'utf8')
describe('Phase 7 property media resilience and operations',()=>{
 it('keeps tenant-scoped session reconciliation and activity TTL safeguards',()=>{const route=read('src/app/module/property/property.route.ts'); const svc=read('src/app/module/websiteBuilder/websiteBuilder.service.ts'); expect(route).toContain("router.get('/assets/session/:sessionId'"); expect(route).toContain("requirePermission('properties.write')"); expect(svc).toContain("organizationId, context: 'property-draft', uploadSessionId"); expect(svc).toContain('latestActivity > cutoff.getTime()'); expect(svc).toContain("intent.status = 'cancelled'")})
 it('claims draft assets transactionally and rejects ownership/session drift',()=>{const c=read('src/app/module/property/property.controller.ts'); const s=read('src/app/module/websiteBuilder/websiteBuilder.service.ts'); expect(c).toContain('session.withTransaction(execute)'); expect(c).toContain('validatePropertyDraftAssets'); expect(c).toContain('claimPropertyDraftAssets'); expect(s).toContain('A property image could not be verified for this tenant'); expect(s).toContain('A property image is not part of this draft session')})
 it('reports durable backup, draft cleanup and asset finalization operations health',()=>{const app=read('src/app.ts'); const worker=read('src/app/module/cron/phase3.worker.ts'); const q=read('src/app/module/operationsQueue/operationsQueue.service.ts'); const status=read('src/app/module/backup/databaseBackup.status.ts'); for(const t of ['lastDatabaseBackupAt','propertyDraftCleanup','propertyMedia']) expect(app).toContain(t); expect(worker).toContain('lastSuccessfulDraftCleanupAt'); expect(q).toContain('pendingAssetFinalizationCount'); expect(q).toContain('property_media_upload_failures_total'); expect(status).toContain('platform_operation_status')})
 it('staging drill performs a real backup/restore and strict critical-record fingerprints',()=>{const drill=read('src/app/module/backup/databaseBackup.drill.ts'); const svc=read('src/app/module/backup/databaseBackup.service.ts'); expect(drill).toContain('DatabaseBackupService.runOnce()'); expect(drill).toContain('BACKUP_DRILL_EXPECT_QUIESCENT'); expect(drill).toContain('fingerprint(sourceDoc) === fingerprint(restoredDoc)'); expect(svc).toContain('assertBackupDatabaseEmpty'); expect(svc).toContain('mongorestore')})
})
