import fs from 'node:fs'
import path from 'node:path'
import { PDFDocument } from 'pdf-lib'
import { describe, expect, it } from 'vitest'
import { SubscriptionReceiptPdfService } from '../../app/module/billing/subscriptionReceiptPdf.service'

const root = process.cwd()
const read = (relative: string) => fs.readFileSync(path.join(root, relative), 'utf8')

const crmReadModel = read('src/app/module/crm/crmListReadModel.service.ts')
const contactService = read('src/app/module/contact/contact.service.ts')
const notificationService = read('src/app/module/notification/notification.service.ts')
const teamViewContract = read('src/app/module/user/user.service.ts')
const subscriptionService = read('src/app/module/subscriptionPayment/subscriptionPayment.service.ts')
const billingController = read('src/app/module/billing/billing.controller.ts')
const receiptService = read('src/app/module/billing/subscriptionReceiptPdf.service.ts')
const brokerService = read('src/app/module/user/user.service.ts')
const viewingService = read('src/app/module/viewing/viewing.service.ts')
const viewingController = read('src/app/module/viewing/viewing.controller.ts')
const domainEvents = read('src/app/module/domainEvent/domainEvent.service.ts')
const realtimeService = read('src/app/module/realtime/realtime.service.ts')

describe('Phase 10 final production acceptance matrix', () => {
  it('Contacts survive aggregate failures, stay tenant scoped and default newest first', () => {
    expect(crmReadModel).toContain('readContactListPageFallback')
    expect(crmReadModel).toContain("logger.warn('crm_contact_read_model_failed'")
    expect(crmReadModel).toContain("sortSpec(options.sortBy, options.sortOrder, CONTACT_SORT_FIELDS, 'updatedAt')")
    expect(crmReadModel).toMatch(/organizationId:\s*options\.organizationId/)
    expect(contactService).toContain("if (!organizationId) throw new ApiError(httpStatus.FORBIDDEN, 'Tenant context is required to list contacts')")
    expect(contactService).toContain("scope: access?.scope || 'team'")
    const integration = read('src/tests/integration/crmPhase14.integration.test.ts')
    expect(integration).toContain('keeps the Contact list available through the resilient fallback for legacy and incomplete records')
    expect(integration).toContain('Phase1 Foreign Tenant Contact')
  })

  it('notification dismissal cannot cross user or tenant boundaries and synchronizes as deleted', () => {
    expect(notificationService).toMatch(/\{ _id: id, organizationId, userId, dismissedAt: null \}/)
    expect(notificationService).toContain("throw new ApiError(404, 'Notification not found')")
    expect(notificationService).toContain("emitNotification(organizationId, userId, row._id.toString(), 'deleted')")
    expect(notificationService).toContain("{ $set: { dismissedAt, readAt: dismissedAt } }")
  })

  it('team role summary counts active tenant users without converting role counts into a shared percentage pool', () => {
    const summaryStart = teamViewContract.indexOf('const getTeamRoleSummary')
    expect(summaryStart).toBeGreaterThan(-1)
    const summary = teamViewContract.slice(summaryStart, teamViewContract.indexOf('const getPublicAgents', summaryStart))
    expect(summary).toContain('organizationId')
    expect(summary).toContain("status: 'active'")
    expect(summary).toContain('$group')
    expect(summary).not.toMatch(/count\s*\/\s*total|count\s*\/\s*members/)
  })

  it('subscription confirmation emits post-commit realtime and acknowledgement is durable per payment/user', () => {
    expect(subscriptionService.indexOf('await CacheInvalidationService.invalidateTenant(organizationId)'))
      .toBeLessThan(subscriptionService.indexOf("type: 'subscription.changed'"))
    expect(subscriptionService).toContain('confirmationNoticeEligible: true')
    expect(subscriptionService).toContain('customerAcknowledgedBy: { $ne: userId }')
    expect(subscriptionService).toContain('$addToSet: { customerAcknowledgedBy: userId }')
    expect(subscriptionService).toContain(".sort({ confirmedAt: -1, _id: -1 })")
    expect(subscriptionService).toContain("SubscriptionPayment.find({ organizationId }).sort({ createdAt: -1, _id: -1 })")
  })

  it('each renewal is independently eligible because confirmation state is stored on the new payment record', () => {
    expect(subscriptionService).toContain('payment.confirmationNoticeEligible = true')
    expect(subscriptionService).toContain('payment.customerAcknowledgedBy = []')
    expect(subscriptionService).toMatch(/\{ organizationId, paymentNumber, status: 'confirmed', confirmationNoticeEligible: true \}/)
  })

  it('receipt endpoint returns an actual PDF attachment and generated bytes have a valid PDF signature', async () => {
    expect(billingController).toContain("res.setHeader('Content-Type', 'application/pdf')")
    expect(billingController).toContain("attachment; filename=\"${receipt.fileName}\"")
    const generated = await SubscriptionReceiptPdfService.generateSubscriptionReceiptPdf({
      receiptNumber: 'RCT-PHASE10',
      paymentNumber: 'PAY-PHASE10',
      status: 'CONFIRMED',
      agencyName: 'Phase 10 Agency',
      customerEmail: 'billing@example.com',
      planName: 'Professional',
      billingCycle: 'yearly',
      periodStart: '2026-08-20T00:00:00.000Z',
      periodEnd: '2027-08-20T00:00:00.000Z',
      paymentMethod: 'bank',
      paymentReference: 'TX-PHASE10',
      paidAt: '2026-08-20T00:00:00.000Z',
      confirmedAt: '2026-08-20T00:05:00.000Z',
      subtotal: 12000,
      vatRate: 0,
      vatAmount: 0,
      total: 12000,
      currency: 'BDT',
    })
    expect(generated.buffer.subarray(0, 5).toString('ascii')).toBe('%PDF-')
    expect(generated.fileName).toBe('opygen-estate-RCT-PHASE10.pdf')
    const pdf = await PDFDocument.load(generated.buffer)
    expect(pdf.getTitle()).toBe('Opygen Estate Receipt RCT-PHASE10')
    expect(pdf.getSubject()).toBe('Subscription Payment Receipt')
  })

  it('receipt layout contains canonical branding plus agency, payment and total fields', () => {
    for (const token of [
      "name: 'OPYGEN ESTATE'",
      "productLine: 'A Product of Opygen'",
      "'Receipt Number'",
      "'Payment Number'",
      "'Agency Name'",
      "'Customer Email'",
      "'Transaction / Reference'",
      "'TOTAL PAID'",
    ]) expect(receiptService).toContain(token)
    expect(receiptService).toContain('input.receiptNumber')
    expect(receiptService).toContain('input.paymentNumber')
    expect(receiptService).toContain('input.agencyName')
  })

  it('public broker list and direct detail are fail-closed unless active, explicitly visible and licensed', () => {
    expect(brokerService).toContain("'agencyOwnerProfile.showAsLicensedBroker': true")
    expect(brokerService).toContain("'agentProfile.showAsLicensedBroker': true")
    expect(brokerService).toContain('const LICENSE_PRESENT = /\\S/')
    expect(brokerService).toContain("status: 'active'")
    expect(brokerService).toContain("throw new ApiError(httpStatus.NOT_FOUND, 'Broker profile not found')")
    expect(brokerService).toContain('RealtimeService.emitPublicOrganization(organizationId, event)')
  })

  it('viewing table stays newest first while calendar is bounded, compact and chronological', () => {
    expect(viewingService).toContain("{ sortBy: 'createdAt', sortOrder: 'desc' }")
    expect(viewingService).toContain("buildAllowedStableSort(sortBy, sortOrder, VIEWING_LIST_SORT_FIELDS, 'createdAt')")
    expect(viewingService).toContain(".select('_id date startTime endTime status clientName propertyId agentId')")
    expect(viewingService).toContain('paginationHelper.buildCalendarSort()')
    expect(viewingController).toContain('MAX_CALENDAR_RANGE_DAYS = 62')
  })

  it('create, update, cancel and delete publish viewing.changed so every open table/calendar cache refreshes', () => {
    expect(viewingService).toContain("eventType:'viewing.scheduled'")
    expect(viewingService).toContain("eventType:payload.status==='Completed'?'viewing.completed':'viewing.updated'")
    expect(viewingService).toContain('changeStatusInTransaction')
    expect(viewingService).toContain('deferPublish:true')
    expect(viewingService).toContain('leadId:linkedLeadId')
    expect(viewingService).toContain("payload.date!==undefined&&date!==String(existing.date)")
    expect(viewingService).toContain("payload.startTime!==undefined&&startTime!==String(existing.startTime)")
    expect(viewingService).toContain("OperationsQueueService.cancel(organizationId,'viewing_reminder',id,{session})")
    expect(viewingService).toContain("eventType:'viewing.deleted'")
    expect(domainEvents).toContain("'viewing.deleted': { type: 'viewing', title: 'Viewing cancelled' }")
    expect(realtimeService).toContain("viewing: 'viewing.changed'")
  })
})
