// Real Studio service with deterministic repository/transaction adapters. Not a MongoDB integration test.
const test = require('node:test'); const assert = require('node:assert/strict'); const crypto = require('node:crypto');
const { createLoader } = require('../phase2/load-typescript.cjs');
let db, failOutbox = false, sequence = 0;
const clone = value => value == null ? value : structuredClone(value);
const get = (doc, key) => key.split('.').reduce((value, part) => value?.[part], doc);
function matches(doc, where) { return Object.entries(where).every(([key, value]) => { if (key === '$or') return value.some(item => matches(doc,item)); const actual = get(doc,key); if (value && typeof value === 'object' && !Array.isArray(value)) { return Object.entries(value).every(([op, operand]) => op === '$exists' ? (actual !== undefined) === operand : op === '$gt' ? actual > operand : op === '$ne' ? JSON.stringify(actual) !== JSON.stringify(operand) : op === '$in' ? operand.includes(actual) : op === '$nin' ? !operand.includes(actual) : JSON.stringify(actual) === JSON.stringify(value)); } return actual === value; }); }
function set(doc, fields) { for (const [key,value] of Object.entries(fields || {})) { const parts = key.split('.'); let parent=doc; for(const part of parts.slice(0,-1)) parent=parent[part] ||= {}; parent[parts.at(-1)] = clone(value); } }
const query = value => { let current=value; const q={ session:()=>q, select:()=>q, limit:n=>{if(Array.isArray(current))current=current.slice(0,n);return q;}, sort:by=>{if(Array.isArray(current))current.sort((a,b)=>{for(const [key,dir] of Object.entries(by)){const diff=get(a,key)>get(b,key)?1:get(a,key)<get(b,key)?-1:0;if(diff)return diff*dir;}return 0;});return q;}, lean:async()=>clone(current), then:(yes,no)=>Promise.resolve(clone(current)).then(yes,no) }; return q; };
function repository(collection) { const all=()=>db[collection]; return {
 findOne:where=>query(all().find(doc=>matches(doc,where)) || null), find:where=>query(all().filter(doc=>matches(doc,where))),
 updateOne:async(where,update,options={})=>{let doc=all().find(item=>matches(item,where));if(!doc && options.upsert){doc={...where};set(doc,update.$setOnInsert);all().push(doc);}if(!doc)return {matchedCount:0};set(doc,update.$set);doc.updatedAt=new Date();return {matchedCount:1};},
 findOneAndUpdate:(where,update)=>{const doc=all().find(item=>matches(item,where));if(doc){set(doc,update.$set);doc.updatedAt=new Date();}return query(doc || null);},
 create:async docs=>docs.map(input=>{const doc={_id:`test-${++sequence}`,createdAt:new Date(),updatedAt:new Date(),...clone(input)};all().push(doc);return {toObject:()=>clone(doc),...doc};}),
 updateMany:async(where,update)=>{for(const doc of all())if(matches(doc,where))set(doc,update.$set);},
 countDocuments:()=>({ maxTimeMS:async()=>1, then:yes=>Promise.resolve(0).then(yes) }),
 }; }
const organizations = repository('org'), studio=repository('studio'), history=repository('history'), receipts=repository('receipts');
const load=createLoader(undefined,{
 crypto, '../organization/organization.model':{Organization:organizations}, '../organization/organization.service':{serializePublicWebsite:(org,stats)=>({...org,stats})},
 '../property/property.model':{Property:repository('properties')}, '../user/user.model':{User:repository('users')},
 './websiteStudio.model':{WebsiteStudio:studio,WebsiteStudioRevision:history,WebsiteStudioReceipt:receipts}, './websitePage.model':{WebsitePage:repository('pages')}, './websiteRevision.model':{WebsiteRevision:repository('pageRevisions')}, './websiteAsset.model':{WebsiteAsset:repository('assets')},
 '../../db/requiredTransaction':{requiredTransaction:async work=>{const previous=clone(db);try{return await work({transaction:true});}catch(error){db=previous;throw error;}}},
 '../audit/audit.service':{writeAudit:async entry=>db.audits.push(entry)}, '../domainEvent/transactionalOutbox.service':{TransactionalOutbox:{emit:async event=>{if(failOutbox)throw new Error('Forced outbox failure');db.events.push(event);}}},
 './websiteDesign.service':{WebsiteDesignService:{validateDraftDesign:async()=>undefined}}, './templateRegistry':{TemplateRegistry:{assertEntitlement:async()=>undefined}},
 './websiteStudio.validation':{studioPatchSchema:{parse:value=>value}},
 './websitePublication.service':{WebsitePublicationService:{commitPublicationState:async({organizationId,set:fields,renderMode,expectedPublicationRevision})=>{const org=db.org.find(item=>item.organizationId===organizationId);if((org.websiteSettings?.publicationRevision||0)!==expectedPublicationRevision)throw new Error('CAS rejected');set(org,fields);org.websiteStatus='published';org.websiteSettings.renderMode=renderMode;org.websiteSettings.publicationRevision=expectedPublicationRevision+1;org.websiteSettings.lastPublishedAt=new Date();return {organization:clone(org),publicationRevision:org.websiteSettings.publicationRevision,lastPublishedAt:org.websiteSettings.lastPublishedAt};}}},
});
const {WebsiteStudioService:service,snapshotForStorage,snapshotFromOrganization,assertStudioRevisions}=load('src/app/module/websiteBuilder/websiteStudio.service.ts');
const request=(state,extra={})=>({expectedDraftRevision:state.draftRevision,expectedPublicationRevision:state.publicationRevision,mutationId:crypto.randomUUID(),...extra});
function reset(){db={org:[{organizationId:'tenant-a',templateId:'template-1',agencyName:'Test agency',logo:'',favicon:'',websiteSettings:{renderMode:'template',publicationRevision:0,content:{home:{heroTitle:'Original live title'}}},updatedAt:new Date()}],studio:[],history:[],receipts:[],pages:[],pageRevisions:[],assets:[],events:[],audits:[],properties:[],users:[]};failOutbox=false;}
test.beforeEach(reset);
test('GET creates no draft and saving creates a draft without publishing or changing mode',async()=>{const initial=await service.getState('tenant-a');assert.equal(db.studio.length,0);const saved=await service.saveDraft('tenant-a',request(initial,{patch:{websiteSettings:{content:{home:{heroTitle:'Draft only'}}}}}));assert.equal(saved.draftRevision,1);assert.equal(db.org[0].websiteSettings.content.home.heroTitle,'Original live title');assert.equal(saved.snapshot.websiteSettings.renderMode,'template');assert.equal(db.events.length,0);});
test('publish commits content/history/receipt/outbox together and retries are idempotent',async()=>{const first=await service.getState('tenant-a');const saved=await service.saveDraft('tenant-a',request(first,{patch:{metaTitle:'Publish this title'}}));const publishRequest=request(saved);const published=await service.publish('tenant-a',publishRequest);assert.equal(db.org[0].metaTitle,'Publish this title');assert.equal(published.publicationRevision,1);assert.equal(published.hasUnpublishedChanges,false);assert.equal(db.history.length,2);assert.equal(db.events.length,1);assert.deepEqual(await service.publish('tenant-a',publishRequest),published);assert.equal(db.events.length,1);assert.equal(db.org[0].websiteSettings.publicationRevision,1);});
test('forced failure after publication changes leaves no partial draft/live/history/receipt writes',async()=>{const initial=await service.getState('tenant-a');const saved=await service.saveDraft('tenant-a',request(initial,{patch:{metaTitle:'Draft title'}}));const before=clone(db);failOutbox=true;await assert.rejects(service.publish('tenant-a',request(saved)),/Forced outbox/);assert.deepEqual(db,before);});
test('two stale writers cannot silently overwrite the saved draft',async()=>{const initial=await service.getState('tenant-a');await service.saveDraft('tenant-a',request(initial,{patch:{metaTitle:'First writer'}}));await assert.rejects(service.saveDraft('tenant-a',request(initial,{patch:{metaTitle:'Second writer'}})),error=>error.statusCode===409);assert.equal(db.studio[0].snapshot.metaTitle,'First writer');});
test('restore changes only the draft until an explicit publication',async()=>{const initial=await service.getState('tenant-a');const saved=await service.saveDraft('tenant-a',request(initial,{patch:{metaTitle:'New live title'}}));const published=await service.publish('tenant-a',request(saved));const restored=await service.restore('tenant-a',{...request(published),revision:0});assert.equal(db.org[0].metaTitle,'New live title');assert.equal(restored.snapshot.metaTitle,'');assert.equal(restored.hasUnpublishedChanges,true);await service.publish('tenant-a',request(restored));assert.equal(db.org[0].metaTitle,'');assert.equal(db.org[0].websiteSettings.publicationRevision,2);});
test('changes from a legacy publisher are detected; reset requires both current revisions',async()=>{const initial=await service.getState('tenant-a');await service.saveDraft('tenant-a',request(initial,{patch:{metaTitle:'Saved'}}));db.org[0].websiteSettings.publicationRevision=5;db.org[0].metaTitle='External publication';const state=await service.getState('tenant-a');assert.equal(state.liveChanged,true);await assert.rejects(service.publish('tenant-a',request(state)),error=>error.statusCode===409);const resetState=await service.resetFromPublished('tenant-a',request(state));assert.equal(resetState.liveChanged,false);assert.equal(resetState.snapshot.metaTitle,'External publication');});
test('foreign images and unready images are rejected, while unchanged legacy image URLs survive',async()=>{db.org[0].logo='https://old.example/logo.png';const initial=await service.getState('tenant-a');await service.saveDraft('tenant-a',request(initial,{patch:{metaTitle:'Legacy preserved'}}));const current=await service.getState('tenant-a');db.assets.push({_id:'a'.repeat(24),organizationId:'tenant-b',url:'https://cdn.example/foreign.jpg',status:'ready'});await assert.rejects(service.saveDraft('tenant-a',request(current,{patch:{logo:'https://cdn.example/foreign.jpg'}})),/library|import/);assert.equal(db.studio[0].snapshot.logo,'https://old.example/logo.png');});
test('purging tenants cannot save and cross-tenant revision IDs do not leak content',async()=>{const initial=await service.getState('tenant-a');await assert.rejects(service.restore('tenant-a',{...request(initial),revision:45}),error=>error.statusCode===404);db.org[0].platformAccess={status:'pending_deletion'};await assert.rejects(service.saveDraft('tenant-a',request(initial,{patch:{metaTitle:'Blocked'}})),error=>error.statusCode===423);});
test('reused mutation ID with different content is rejected',async()=>{const initial=await service.getState('tenant-a');const input=request(initial,{patch:{metaTitle:'First'}});await service.saveDraft('tenant-a',input);await assert.rejects(service.saveDraft('tenant-a',{...input,patch:{metaTitle:'Different'}}),error=>error.statusCode===409);});
test('media and section slot maps are nested for storage and normalize losslessly',()=>{const snapshot=snapshotFromOrganization(db.org[0]);snapshot.websiteSettings.media={'home.heroImage':{alt:'Own photo',decorative:false,focalPoint:{x:10,y:90},fit:'contain'}};snapshot.websiteSettings.sectionStyles={'home.hero':{backgroundColor:'#123456'}};const stored=snapshotForStorage(snapshot);assert(!Object.keys(stored.websiteSettings.media).some(key=>key.includes('.')));assert(!Object.keys(stored.websiteSettings.sectionStyles).some(key=>key.includes('.')));assert.deepEqual(snapshotFromOrganization(stored),snapshot);});
test('all Studio routes enforce website.write at the API boundary',()=>{const fs=require('node:fs');const path=require('node:path');const {root}=require('../phase2/load-typescript.cjs');const lines=fs.readFileSync(path.join(root,'src/app/module/websiteBuilder/websiteBuilder.route.ts'),'utf8').split('\n').filter(line=>/router\.(get|post|put).*'\/studio/.test(line));assert.equal(lines.length,8);for(const line of lines)assert(line.includes("requirePermission('website.write')"));});
