const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const read = (file) => fs.readFileSync(file, 'utf8')

test('release monitoring covers publish, public forms, public catalog and image delivery', () => {
  const events = read('src/shared/productionEvents.ts')
  const handler = read('src/app/middlewares/globalErrorHandler.ts')
  const observability = read('src/app/module/observability/observability.route.ts')
  for (const event of ['website_publish_failed', 'public_form_failed', 'public_property_query_failed', 'website_image_delivery_failed']) assert.match(events, new RegExp(`'${event}'`))
  assert.match(handler, /website\/studio\/publish/)
  assert.match(handler, /viewing\/public-request/)
  assert.match(handler, /lead\/public-capture/)
  assert.match(handler, /property\/public/)
  assert.match(observability, /website_image_delivery_failed/)
})

test('renderer binding migration is dry-run first and backs up every affected collection before apply', () => {
  const migration = read('src/app/db/migratePhase5WebsiteRenderer.ts')
  assert.match(migration, /if \(!cli\.apply\)/)
  assert.match(migration, /backupDocuments/)
  assert.match(migration, /writeMigrationManifest/)
  assert.match(migration, /organizations/)
  assert.match(migration, /websitestudios/)
  assert.match(migration, /websitestudiorevisions/)
  assert.match(migration, /LEGACY_WEBSITE_RENDERER_VERSION/)
  assert.match(migration, /existingTenantDesignChanges:\s*0/)
  assert.doesNotMatch(migration, /\$unset|templateId\s*:|websiteSettings\.content\s*:|websiteSettings\.branding\s*:/)
})
