import httpStatus from 'http-status'
import ApiError from '../../../errors/ApiError'
import { IGenericResponse, IPaginationOptions } from '../../../interfaces/common'
import paginationHelper from '../../helpers/paginationHelper'
import { CrmService } from '../crm/crm.service'
import { DomainEventService } from '../domainEvent/domainEvent.service'
import { OperationsQueueService } from '../operationsQueue/operationsQueue.service'
import { ITask, ITaskFilter } from './task.interface'
import { Task } from './task.model'
const dueAt=(date:string,time='09:00')=>new Date(`${date}T${time}:00+06:00`)
const scheduleReminder=async(task:any)=>{const config:any=await CrmService.getConfig(task.organizationId);const runAt=new Date(dueAt(task.dueDate,task.dueTime).getTime()-(config.reminders?.taskMinutesBefore||0)*60_000);await OperationsQueueService.schedule({organizationId:task.organizationId,type:'task_reminder',entityId:task._id.toString(),runAt,payload:{assignedAgent:task.assignedAgent?.toString()}})}
const createTask=async(organizationId:string,payload:Partial<ITask>,actorId?:string):Promise<ITask>=>{const result:any=await Task.create({...payload,organizationId});await scheduleReminder(result);await DomainEventService.emit({organizationId,aggregateType:'task',aggregateId:result._id.toString(),eventType:'task.created',leadId:result.linkedLead?.toString(),propertyId:result.linkedProperty?.toString(),actorId:actorId||result.assignedAgent?.toString(),payload:{summary:`Task created: ${result.title}`,dueDate:result.dueDate,dueTime:result.dueTime,priority:result.priority}});return result}
const getAllTasks=async(filters:ITaskFilter,paginationOptions:IPaginationOptions):Promise<IGenericResponse<ITask[]>>=>{const{searchTerm,organizationId,status,priority,assignedAgent,linkedLead,linkedProperty,dueDate}=filters;const c:any[]=[];if(organizationId)c.push({organizationId});if(searchTerm)c.push({$or:['title','description'].map(field=>({[field]:{$regex:searchTerm,$options:'i'}}))});if(status)c.push({status});if(priority)c.push({priority});if(assignedAgent)c.push({assignedAgent});if(linkedLead)c.push({linkedLead});if(linkedProperty)c.push({linkedProperty});if(dueDate)c.push({dueDate});const where=c.length?{$and:c}:{};const{page,limit,skip,sortBy,sortOrder}=paginationHelper.calculatePagination(paginationOptions);const[result,total]=await Promise.all([Task.find(where).populate('assignedAgent','name email profileImgURL').populate('linkedLead','name phone email').populate('linkedProperty','title price').sort({dueDate:1,[sortBy]:sortOrder}).skip(skip).limit(limit),Task.countDocuments(where)]);return{meta:{page,limit,total},data:result}}
const updateTask=async(organizationId:string,id:string,payload:Partial<ITask>,actorId?:string):Promise<ITask|null>=>{const existing:any=await Task.findOne({_id:id,organizationId});if(!existing)throw new ApiError(httpStatus.NOT_FOUND,'Task not found');if(payload.status==='Completed'&&!payload.completedAt)payload.completedAt=new Date();const result:any=await Task.findOneAndUpdate({_id:id,organizationId},payload,{new:true}).populate('assignedAgent','name email profileImgURL').populate('linkedLead','name phone email').populate('linkedProperty','title price');if(['Completed','Cancelled'].includes(result.status))await OperationsQueueService.cancel(organizationId,'task_reminder',id);else if(payload.dueDate||payload.dueTime)await scheduleReminder(result);const eventType=result.status==='Completed'&&existing.status!=='Completed'?'task.completed':'task.updated';await DomainEventService.emit({organizationId,aggregateType:'task',aggregateId:id,eventType,leadId:result.linkedLead?String((result.linkedLead as any)._id||result.linkedLead):undefined,propertyId:result.linkedProperty?String((result.linkedProperty as any)._id||result.linkedProperty):undefined,actorId,payload:{summary:`Task ${result.status}: ${result.title}`,status:result.status}});return result}
const deleteTask=async(organizationId:string,id:string)=>{const result=await Task.findOneAndDelete({_id:id,organizationId});if(!result)throw new ApiError(404,'Task not found');await OperationsQueueService.cancel(organizationId,'task_reminder',id);return result}
const approveTask=async(organizationId:string,id:string,userId:string,approvalStatus:'approved'|'rejected')=>{const result=await Task.findOneAndUpdate({_id:id,organizationId},{approvalStatus,approvedBy:userId,approvedAt:new Date()},{new:true}).populate('assignedAgent','name email profileImgURL').populate('approvedBy','name email profileImgURL');if(!result)throw new ApiError(404,'Task not found');return result}
export const TaskService={createTask,getAllTasks,updateTask,deleteTask,approveTask}
